# Site settings
title: Micah Bunting
email: amnykon@gmail.com
#description: "Edit description in _config.yml"
#info: "Edit this info in _config.yml"
#message: "Edit this message in _config.yml"
keywords: "mac,apple,iphone,ios,osx,games,apps,development"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.delightfuldev.com" # the base hostname & protocol for your site
linkedin_username: micahbunting
resume_site: /documents/MicahBuntingResume.pdf
# Build settings
markdown: kramdown
author:
    name: Micah Bunting
    header_bg: /images/profile-header.png
    avatar: /images/avatar.jpg
    email: amnykon@gmail.com
